spring:
  application:
    name: pedidos
  datasource:
    url: jdbc:postgresql://localhost:8020/icompraspedidos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8051

icompraspedidos:
  client:
    clientes:
      url: http://localhost:8040
    produtos:
      url: http://localhost:8030
  pagamentos:
    apikey: 4f8b3c2a1d6e9f0b1234567890abcdef
  config:
    kafka:
      topics:
        envio: icompras.pedido-enviado
        pagamento: icompras.pedido-pago
        faturamento: icompras.pedido-faturado
      url: localhost:8021