version: '3.9'

services:
  zookeepercp:
    image: confluentinc/cp-zookeeper:7.2.15
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "8023:2181"

  kafkabroker:
    image: confluentinc/cp-kafka:7.2.15
    depends_on:
      - zookeepercp
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeepercp:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkabroker:9092, PLAINTEXT_HOST://localhost:8021
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "8021:29092"

  kafkaui:
    image: provectuslabs/kafka-ui:v0.7.2
    depends_on:
      - kafkabroker
    environment:
      KAFKA_CLUSTERS_0_NAME: processamento
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafkabroker:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeepercp:2181
    ports:
      - "8022:8080"